### ISSUE TITLE
"Could not find execution log ... Removing environment" warnings

### ISSUE THREAD

**Issue by jzwinck** [conda-tools/conda-execute#39]
I recently upgraded from 0.4 to 0.8.0 to fix #37.  Now I get a warning message from many of my conda-execute jobs:

    Could not find execution log for /home/foo/conda/tmp_envs/928ef5960cc02406912e. Removing environment.
    WARNING conda-tmpenv:cleanup_tmp_envs(216): Could not find execution log for /home/srv_hachiko/conda/tmp_envs/928ef5960cc02406912e. Removing environment.

I have no idea what this means.  It happens a lot, but not every time a job runs.  I've seen it happen in jobs launched by cron and also sometimes when running the same command in the terminal directly.

The cron jobs look like this:

    16 07-17 * * 1-5 ~/conda/bin/conda-execute ~/foo/bar

The command being run is a simple Python script.  It starts out like this:

    #!/usr/bin/env python3
    # conda execute
    # env:
    # - python >=3
    # - requests

When I get one of these messages, it seems there is a corresponding file like ~/conda/tmp_envs/.conda-lock_928ef5960cc02406912e.  I don't know if this is expected.

I am using Conda 4.2.13 and Python 2.7 (yes, different Python to the one inside the script being run by conda-execute) on CentOS 7.

**Comment by jzwinck** [comment]
@pelson Do you have any idea about this?  It's really quite annoying now--I upgraded conda-execute to fix #37 where a spurious error would occur occasionally.  Now I get spurious errors all the time!

**Comment by pelson** [comment]
I've been somewhat AWOL for the best part of 6 months, sorry about the lack of response. Honestly, I don't know precisely what is going on here.

The lock file you mention comes from https://github.com/pelson/conda-execute/blob/master/conda_execute/tmpenv.py#L139. Would be interesting to know what ```conda_execute.tpmenv.envs_and_running_pids``` gives when this occurs. Are you, by any chance, in a position to do a little more digging in order to make this entirely repeatable?

**Comment by jzwinck** [comment]
@pelson I can't do much more with this - I decided not to use conda-execute anymore.  Partly due to this bug, partly I just outgrew it and found other solutions worked better for my current needs.

**Comment by jzwinck** [comment]
Closing because I am no longer interested in this issue, and perhaps no one else is either.
