### ISSUE TITLE
Issues with noarch python packages

### ISSUE THREAD

**Issue by jakirkham** [conda-tools/conda-execute#46]
Seems we are running into some issues installing noarch python packages with `conda-execute`.

ref: https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/274023288#L1203

cc @isuruf

**Comment by isuruf** [comment]
I don't see an update conda command there. Should do an update conda command before running `conda-execute`. Maybe `conda-execute` itself can run `conda update conda` before doing anything.

**Comment by jakirkham** [comment]
It's using [`conda` 4.3.21]( https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/274023288#L1158 ) as long as I'm not missing a step that changed the version. Should be new enough I think. The environment itself should have `conda` 4.3.22, but the `conda` used by `conda-execute` should be the one doing the actual install.

**Comment by isuruf** [comment]
Yes, this is a problem with conda-execute. It fails at link step in `_create_env_conda_43`

**Comment by lbdreyer** [comment]
I have put up PR #48 which appears to fix this problem.

I have tested it with `funcsigs`, `anaconda-client` and `cherrypy` which are all noarch packages

**Comment by pelson** [comment]
Fixed with #48. Thanks @lbdreyer
