### ISSUE TITLE
v0.8.2 release?

### ISSUE THREAD

**Issue by bjlittle** [conda-tools/conda-execute#49]
Now that https://github.com/conda-tools/conda-execute/pull/48 has been merged, it would be super helpful to tag a release so that the `noarch` issue fix is available via `conda-forge` ...

@conda-tools/core

**Comment by jakirkham** [comment]
+1 from me.

**Comment by pelson** [comment]
Just tagged a v0.8.2. @djkirkham has an interest in updating https://github.com/conda-forge/conda-execute-feedstock

**Comment by bjlittle** [comment]
@jakirkham and @pelson Great, thanks! 👍
